In [1]:
# linear algebra 
import tensorflow as tf
import numpy as np

x1 = tf.constant([[1,2],
                   [3,5]])
x2 = tf.constant([[1,2],
                   [3,5]])
print(x1.shape,x2.shape)
print(tf.linalg.matmul(x1,x2))
print(tf.transpose(x1))
print(tf.linalg.adjoint(x1))
print(tf.transpose(x2)@tf.transpose(x1))
tf.linalg.matmul(x2,x1,transpose_a=False,transpose_b=False,adjoint_a=False,adjoint_b=False)

# we can also get other things like rank learn them later
# there are also functions like concat/stack reshape and change dimensions and squeeze , apply padding ,  learn about them later

# ragged tensors
# Ragged tensors are tensors with variable-length dimensions, which allows you to represent non-uniform data. This is useful for data where each entry might have a different length, such as sentences with different numbers of words.
# Creating a ragged tensor
ragged_tensor = tf.ragged.constant([[1, 2, 3], [], [4, 5], [6]])
print(ragged_tensor)
# Output: <tf.RaggedTensor [[1, 2, 3], [], [4, 5], [6]]>
print(ragged_tensor.shape)
# Output: (4, None) indicating 4 rows with varying column sizes

# sparse tensors
# Sparse tensors are tensors that are mostly composed of zeros or empty elements. Instead of storing all elements, they store only the indices and values of the non-zero elements, saving memory and computational resources.

# Creating a sparse tensor
sparse_tensor = tf.SparseTensor(indices=[[0, 0], [1, 2], [2, 3]],
                                values=[1, 2, 3],
                                dense_shape=[3, 4])

print(sparse_tensor)
# Output: SparseTensor(indices=tf.Tensor(
# [[0 0]
#  [1 2]
#  [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 3], shape=(3,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

# Convert sparse tensor to dense tensor to see the full representation
dense_tensor = tf.sparse.to_dense(sparse_tensor)
print(dense_tensor)
# Output: 
# [[1 0 0 0]
#  [0 0 2 0]
#  [0 0 0 3]]

# string tensors
# String tensors are tensors that contain string data. These are useful for processing text data in machine learning models.

# Creating a string tensor
string_tensor = tf.constant(["TensorFlow", "is", "awesome!"])

print(string_tensor)
# Output: tf.Tensor([b'TensorFlow' b'is' b'awesome!'], shape=(3,), dtype=string)

# Operations on string tensors
uppercase_tensor = tf.strings.upper(string_tensor)
print(uppercase_tensor)
# Output: tf.Tensor([b'TENSORFLOW' b'IS' b'AWESOME!'], shape=(3,), dtype=string)

# Splitting strings into substrings
split_tensor = tf.strings.split(string_tensor)
print(split_tensor)
# Output: 
# SparseTensor(indices=tf.Tensor(
# [[0 0]
#  [1 0]
#  [2 0]], shape=(3, 2), dtype=int64), values=tf.Tensor([b'TensorFlow' b'is' b'awesome!'], shape=(3,), dtype=string), dense_shape=tf.Tensor([3 1], shape=(2,), dtype=int64))

# Convert to dense tensor to see the full representation
dense_split_tensor = tf.sparse.to_dense(split_tensor, default_value="")
print(dense_split_tensor)
# Output: 
# [[b'TensorFlow']
#  [b'is']
#  [b'awesome!']]


(2, 2) (2, 2)
tf.Tensor(
[[ 7 12]
 [18 31]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 3]
 [2 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 3]
 [2 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 18]
 [12 31]], shape=(2, 2), dtype=int32)
<tf.RaggedTensor [[1, 2, 3], [], [4, 5], [6]]>
(4, None)
SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 3], shape=(3,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 3]], shape=(3, 4), dtype=int32)
tf.Tensor([b'TensorFlow' b'is' b'awesome!'], shape=(3,), dtype=string)
tf.Tensor([b'TENSORFLOW' b'IS' b'AWESOME!'], shape=(3,), dtype=string)
<tf.RaggedTensor [[b'TensorFlow'],
 [b'is'],
 [b'awesome!']]>


TypeError: Input must be a SparseTensor.